"""A factory for compiling and persisting declarative footnote strategies.

This module provides the `StructuralStrategyCompiler`, a component responsible
for the lifecycle of declarative normalization parameters. It acts as a pure
mathematical factory: it takes the structural invariants isolated by the
`ForensicPatternAnalyzer` and packages them into clean JSON data schemas
compatible with the native parameterized strategies.

Analytical Blueprint:
---------------------

Based on the specification, the following logic will be mapped:

Global Free Functions (Module Level):
    - None present in the skeleton.

Class Methods (StructuralStrategyCompiler):
    - __init__: Initializes the compiler by resolving the `footnote_registry_path` from the shared `BookStyleContext`.
    - compile_footnote_strategy: Orchestrates the compilation. It generates a unique `pattern_id` via an MD5 hash,
    builds a robust CSS selector for the note body using `_build_body_selector`, and constructs the final configuration
    dictionary, which is returned to the caller.
    - _build_body_selector: Implements the priority-based logic for creating a robust CSS selector for a sample note body tag,
    raising `ForensicAnalysisError` if a sufficiently specific selector cannot be created.
"""

from __future__ import annotations

import hashlib
import logging
from typing import Any

from bs4 import Tag

from dom_normalizer.core import BookStyleContext
from dom_normalizer.core.dom_utils import coerce_class_list

log = logging.getLogger(__name__)


class ForensicAnalysisError(Exception):
    """Raised when the forensic analyzer encounters an irreconcilable mathematical violation in the DOM."""


class RegistryWriteError(Exception):
    """Raised when the atomic persistence to the JSON registry file fails or suffers a collision."""


class StructuralStrategyCompiler:
    """Compiles and persists declarative footnote strategies from forensic analysis.

    This class acts as a factory that takes the structural invariants discovered
    by the `ForensicPatternAnalyzer` and transforms them into a declarative,
    JSON-serializable configuration. This configuration is then atomically
    persisted to a central registry file, allowing the `FootnoteProcessor` to
    use it in future runs as a `ParameterizedFootnoteStrategy`.

    This data-driven approach allows the system to learn new footnote patterns
    without requiring code changes.

    Attributes:
        context (BookStyleContext): The shared context for the book, providing
            access to global configuration like the registry path.
        footnote_registry_path (Path): The resolved path to the JSON footnote
            pattern registry.
    """

    def __init__(self, context: BookStyleContext) -> None:
        """Initializes the compiler with the book's context.

        Args:
            context (BookStyleContext): The shared context for the book, providing
                access to the engine's configuration, including the path to the
                footnote registry.
        """
        self.context = context

    def compile_footnote_strategy(
        self,
        _sample_callout: Tag,
        sample_body: Tag,
        detected_selector: str,
        topology_location: str,
    ) -> tuple[str, dict[str, Any]]:
        """Compiles a strategy from forensic data.

        This method takes the pure structural invariants isolated by the
        `ForensicPatternAnalyzer`, generates a declarative configuration
        dictionary, which is returned to the caller.

        Args:
            _sample_callout (Tag): A sample `<a>` tag representing a footnote
                callout. Reserved for future enhancements (e.g., backlink
                selector compilation) but currently unused.
            sample_body (Tag): A sample tag representing the corresponding note body.
            detected_selector (str): The CSS selector that identifies callout `<a>` tags.
            topology_location (str): The location of note bodies ('donor_file' or
                'end_of_section').

        Returns:
            tuple[str, dict[str, Any]]: A tuple containing the generated
                `pattern_id` and the new strategy configuration.

        Raises:
            ForensicAnalysisError: If a robust selector for the note body
                cannot be generated by `_build_body_selector`.
            Exception: Per Global Directive #1, any unexpected native exceptions
                will be caught, logged as CRITICAL, and re-raised.

        Mutations:
            None. This method is a pure function that does not mutate state or
            the file system.

        Rules & Limits:
            - Pattern ID Generation: A unique `pattern_id` is generated with
              the format `param_fn_{hash}`, where `{hash}` is the first 16
              characters of the SHA-256 hash of `f"{detected_selector}_{topology_location}"`.
            - Configuration Schema: The generated dictionary must conform to the
              structure defined in the specification, including the `pattern_id`
              and a `forensic_signature` sub-dictionary.
        """
        # Generate a unique ID for the pattern
        hash_source = f"{detected_selector}_{topology_location}".encode()
        pattern_hash = hashlib.sha256(hash_source).hexdigest()[:16]
        pattern_id = f"param_fn_{pattern_hash}"

        # Build a robust selector for the note body
        body_selector = self._build_body_selector(sample_body)

        # Construct the new configuration dictionary
        new_config = {
            "pattern_id": pattern_id,
            "forensic_signature": {
                "callout_selector": detected_selector,
                "body_selector": body_selector,
                "body_topology_location": topology_location,
            },
        }

        return pattern_id, new_config

    def _build_body_selector(self, sample_body: Tag) -> str:
        """Generates a robust, specific CSS selector for a sample note body tag.

        This method implements a priority-based algorithm to create a CSS
        selector that is specific enough to avoid collisions but general enough
        to identify all similar note bodies.

        Args:
            sample_body (Tag): A sample tag representing a footnote body.

        Returns:
            str: A CSS selector string.

        Raises:
            ForensicAnalysisError: If the `sample_body` tag is too generic (e.g.,
                a bare `<div>` with no class, ID, or specific parent) to create a
                structurally safe selector.

        Mutations:
            None.

        Rules & Limits:
            - Selector Priority Order:
              1. **ID-based:** If the tag has an `id`, this is the most specific
                 and is preferred.
              2. **Class-based:** If the tag has a `class` attribute, this is the
                 second choice.
              3. **Parent-based:** If the tag has a specific parent, this is used
                 as a fallback.
              4. **Failure:** If none of the above can produce a safe selector,
                 a `ForensicAnalysisError` is raised.
            - Node Type Safety: Expects a `Tag` object. Behavior is undefined for
              a `NavigableString`.
        """
        # Priority 1: ID-based
        if (body_id := sample_body.get("id")) is not None:
            # BeautifulSoup can return a list for multi-valued attributes, even
            # though 'id' should be single-valued. A list-valued 'id' indicates
            # malformed HTML, so we deliberately treat it as invalid and fall
            # back to the next selector strategy rather than coercing it.
            if isinstance(body_id, list):
                log.warning(
                    "Encountered list-valued id attribute on %s; treating as invalid and falling back",
                    sample_body,
                )
                body_id = None
            if body_id:
                return f"{sample_body.name}#{body_id}"

        # Priority 2: Class-based
        if classes := coerce_class_list(sample_body.get("class")):
            # Normalize class order so semantically equivalent elements
            # with different class attribute ordering produce stable selectors.
            sorted_classes = sorted(classes)
            class_selector = "." + ".".join(sorted_classes)
            return f"{sample_body.name}{class_selector}"

        # Priority 3: Parent-based
        if sample_body.parent and sample_body.parent.name != "[document]":
            parent = sample_body.parent
            parent_selector = parent.name

            # Incorporate parent ID for stronger specificity when available
            if p_id_raw := parent.get("id"):
                p_id = p_id_raw[0] if isinstance(p_id_raw, list) else p_id_raw
                parent_selector += f"#{p_id}"

            if p_classes := coerce_class_list(parent.get("class")):
                parent_selector += "." + ".".join(p_classes)

            return f"{parent_selector} > {sample_body.name}"

        # Priority 4: Failure
        raise ForensicAnalysisError(
            "Could not build a robust selector for the sample note body. "
            f"The tag is too generic (e.g., a bare <{sample_body.name}> with no class, ID, "
            "or specific parent).",
        )
