"""Test Suite Orchestrator for DOM Normalizer.

This module orchestrates the generation of test suites from source or skeleton files using
Ollama models. It supports multi-pass execution: Return Value testing (R) and
DOM Mutation testing (M).

Analytical Blueprint:
---------------------

This script automates the generation of YAML test suites for Python modules by
leveraging local Ollama models.

- **Objective:** To generate specification and mutation tests for Python
  functions and classes based on their source code and docstrings.
- **Components:**
  - `run_pipeline`: Main orchestrator that manages file I/O and processing flow.
  - `get_public_definitions`: Uses Python's `ast` module to parse source files
    and extract public functions, classes, and methods.
  - `call_ollama`: Handles HTTP communication with the Ollama API.
- **Analytical Steps:**
  1. Parse command-line arguments to determine the execution mode ('R' or 'M').
  2. Load mode-specific configurations (prompts, input/output directories).
  3. Scan the input directory for Python files that need test generation.
  4. Group pending modules by the assigned Ollama model from `model_routes.json`.
  5. For each module, extract public definitions into a JSON payload.
  6. Send the payload and a skill prompt to the Ollama API for inference.
  7. Save the generated YAML snippet to the corresponding output file.
"""

import argparse
import ast
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import requests

# Configuración de modos de ejecución
MODE_CONFIGS = {
    "R": {
        "prompt_path": "prompts/generate_return_tests.md",
        "input_dir": "skeletons",
        "output_dir": "tests/specs/returns",
        "description": "Pass 1: Return Value Tests (Specification / Contract)",
    },
    "M": {
        "prompt_path": "prompts/generate_mutation_tests.md",
        "input_dir": "src",
        "output_dir": "tests/specs/mutations",
        "description": "Pass 2: DOM Mutation Tests (Implementation / Real Code)",
    },
}

DEFAULT_MODEL_TAG_MAP = {
    "1.5B": "qwen2.5-coder:1.5b-instruct",
    "3B": "qwen2.5-coder:3b-instruct",
    "14B": "qwen2.5-coder:14b-instruct",
}

OLLAMA_API_URL: str = "http://localhost:11434/api/generate"
MODEL_ROUTES_CONFIG_PATH: str = "model_routes.json"


class OllamaGenerationError(Exception):
    """Custom exception for errors related to the Ollama API."""


def load_skill_prompt(prompt_path: str) -> str:
    """Loads the content of the Markdown-based skill prompt.

    Args:
        prompt_path: The file system path to the skill prompt Markdown file.

    Returns:
        The content of the file as a string.

    Raises:
        FileNotFoundError: If the prompt file does not exist at the given path.
    """
    path = Path(prompt_path)
    if path.exists():
        with open(path, encoding="utf-8") as f:
            return f.read()
    raise FileNotFoundError(f"Skill prompt not found at: {prompt_path}")


def call_ollama(
    model_alias: str,
    skill_prompt: str,
    target_payload: str,
    model_map: dict[str, str] | None = None,
) -> str:
    """Performs the HTTP call to Ollama using the requests library.

    Args:
        model_alias: The alias of the model to use (e.g., "1.5B").
        skill_prompt: The main prompt with instructions.
        target_payload: The specific content (code/definition) to process.
        model_map: A dictionary to map aliases to actual model names.

    Returns:
        The text response generated by the model.

    Raises:
        OllamaGenerationError: If a connection error, HTTP error, or an empty
            response from the model occurs.
    """
    if model_map is None:
        model_map = DEFAULT_MODEL_TAG_MAP

    actual_model = model_map.get(model_alias, model_alias)

    full_prompt = f"{skill_prompt}\n\n[OBJETIVO A PROCESAR]:\n{target_payload}"

    options = {
        "num_predict": 2048,
        "stop": ["<|im_end|>", "<|endoftext|>"],
        "min_p": 0.05,
        "repeat_penalty": 1.1,
    }

    payload = {
        "model": actual_model,
        "prompt": full_prompt,
        "stream": False,
        "options": options,
    }

    try:
        # Set a reasonable timeout (e.g., 120 seconds)
        response = requests.post(OLLAMA_API_URL, json=payload, timeout=120)
        response.raise_for_status()  # Raises an HTTPError for bad responses (4xx or 5xx)

        data = response.json()
        if response_text := data.get("response", "").strip():
            return response_text

        raise OllamaGenerationError(
            f"Ollama returned an empty response for model '{actual_model}'",
        )

    except requests.exceptions.HTTPError as e:
        # If there's no response object, we can't get more details.
        if not e.response:
            raise OllamaGenerationError(
                f"HTTP error from Ollama with model '{actual_model}' (no response body): {e}",
            ) from e

        # Try to get a more specific error message from the response body
        try:
            err_json = e.response.json()
            err_msg = err_json.get("error", e.response.text)
        except requests.exceptions.JSONDecodeError:
            err_msg = e.response.text

        raise OllamaGenerationError(
            f"HTTP {e.response.status_code} error from Ollama with model '{actual_model}': {err_msg}",
        ) from e

    except requests.exceptions.RequestException as e:
        # Catches connection errors, timeouts, etc.
        raise OllamaGenerationError(
            f"Could not connect to Ollama at {OLLAMA_API_URL}. Is the service running? Detail: {e}",
        ) from e


def _parse_function_def(node: ast.FunctionDef) -> dict[str, str]:
    """Parses a function definition node.

    Args:
        node: The `ast.FunctionDef` node to parse.

    Returns:
        A dictionary containing the function's type, name, and docstring.
    """
    docstring = ast.get_docstring(node)
    return {
        "type": "function",
        "name": node.name,
        "docstring": docstring or "No docstring available.",
    }


def _parse_class_def(node: ast.ClassDef) -> dict[str, Any]:
    """Parses a class definition node, including its public methods.

    Args:
        node: The `ast.ClassDef` node to parse.

    Returns:
        A dictionary containing the class's type, name, docstring, and a list
        of its public methods.
    """
    class_docstring = ast.get_docstring(node)
    methods = []
    for subnode in node.body:
        if isinstance(subnode, ast.FunctionDef) and not subnode.name.startswith(
            "_",
        ):
            m_docstring = ast.get_docstring(subnode)
            methods.append(
                {
                    "name": subnode.name,
                    "docstring": m_docstring or "No docstring available.",
                },
            )
    return {
        "type": "class",
        "name": node.name,
        "docstring": class_docstring or "No docstring available.",
        "methods": methods,
    }


def get_public_definitions(py_path: Path) -> list[dict[str, Any]]:
    """Parses the AST of a .py file to extract public functions and methods.

    Args:
        py_path: The path to the Python file to parse.

    Returns:
        A list of dictionaries, where each dictionary represents a public
        function or class found in the file.
    """
    with open(py_path, encoding="utf-8") as f:
        tree = ast.parse(f.read(), filename=str(py_path))

    definitions = []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            definitions.append(_parse_function_def(node))
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            definitions.append(_parse_class_def(node))

    return definitions


def _setup_pipeline_context(mode: str) -> dict[str, Any]:
    """Validates mode and loads all necessary configurations for the pipeline.

    Args:
        mode: The execution mode ('R' for Returns, 'M' for Mutations).

    Returns:
        A dictionary containing the pipeline context, including paths, the
        skill prompt, and model routing information.

    Raises:
        ValueError: If an invalid mode is provided.
        FileNotFoundError: If the skill prompt file is not found.
    """
    mode_key = mode.upper()
    if mode_key not in MODE_CONFIGS:
        raise ValueError(f"Invalid mode '{mode}'. Allowed options: 'R' or 'M'.")

    cfg = MODE_CONFIGS[mode_key]
    print(f"\n=== Starting pipeline: {cfg['description']} ===")

    input_path = Path(cfg["input_dir"])
    output_path = Path(cfg["output_dir"])
    output_path.mkdir(parents=True, exist_ok=True)

    skill_prompt = load_skill_prompt(cfg["prompt_path"])

    routes = {}
    if Path(MODEL_ROUTES_CONFIG_PATH).exists():
        with open(MODEL_ROUTES_CONFIG_PATH, encoding="utf-8") as f:
            routes = json.load(f)

    return {
        "input_path": input_path,
        "output_path": output_path,
        "skill_prompt": skill_prompt,
        "routes": routes,
    }


def run_pipeline(
    mode: str = "R",
    model_map: dict[str, str] | None = None,
):
    """Orchestrates the test suite generation based on the selected mode (R or M).

    Args:
        mode: The execution mode ('R' for Returns, 'M' for Mutations). Defaults to "R".
        model_map: An optional dictionary to map model aliases to actual model names.
            If not provided, `DEFAULT_MODEL_TAG_MAP` is used.
    """
    context = _setup_pipeline_context(mode)

    if model_map is None:
        model_map = DEFAULT_MODEL_TAG_MAP

    pending_modules = _collect_pending_modules(
        context["input_path"],
        context["output_path"],
        context["routes"],
    )
    model_groups = _group_by_model(pending_modules)

    print(f"Source directory: {context['input_path']}")
    print(f"Output directory: {context['output_path']}")
    print(f"Prompt used:      {context['skill_prompt']}")
    print(f"Pending modules:  {len(pending_modules)}")

    for model, mods in model_groups.items():
        print(f" -> Group [{model}]: {len(mods)} modules ready for inference.")

    for model_alias, mods in model_groups.items():
        _process_model_group(model_alias, mods, context["skill_prompt"], model_map)


def _collect_pending_modules(
    input_path: Path, output_path: Path, routes: dict[str, str]
) -> list[dict[str, Any]]:
    """Collects modules that need test generation.

    Args:
        input_path: The root directory of the source files.
        output_path: The root directory for the generated test files.
        routes: A dictionary mapping module keys to model aliases.

    Returns:
        A list of dictionaries, each representing a module that needs to have
        tests generated.
    """
    pending = []
    for py_file in input_path.rglob("*.py"):
        rel_path = py_file.relative_to(input_path)
        yaml_file = output_path / rel_path.with_suffix(".yaml")

        if (
            not yaml_file.exists()
            or py_file.stat().st_mtime > yaml_file.stat().st_mtime
        ):
            module_key = str(rel_path.with_suffix("")).replace("/", ".")
            assigned_model = routes.get(module_key, "1.5B")
            pending.append(
                {
                    "py_path": py_file,
                    "yaml_path": yaml_file,
                    "module_key": module_key,
                    "model": assigned_model,
                },
            )
    return pending


def _group_by_model(
    pending_modules: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    """Groups pending modules by their assigned model.

    Args:
        pending_modules: A list of modules to be processed.

    Returns:
        A dictionary where keys are model aliases and values are lists of
        modules assigned to that model.
    """
    groups = defaultdict(list)
    for mod in pending_modules:
        groups[mod["model"]].append(mod)
    return groups


def _generate_yaml_for_module(
    mod: dict[str, Any],
    model_alias: str,
    skill_prompt: str,
    model_map: dict[str, str] | None,
) -> str | None:
    """Generates the full YAML content for a single module, if possible.

    Args:
        mod: A dictionary containing information about the module to process.
        model_alias: The alias of the model to use for generation.
        skill_prompt: The main prompt with instructions for the model.
        model_map: An optional dictionary to map model aliases to actual model names.

    Returns:
        The complete YAML content as a string if generation is successful,
        otherwise `None`.
    """
    definitions = get_public_definitions(mod["py_path"])
    if not definitions:
        print(f"   [SKIPPED] No public functions/methods in {mod['py_path']}")
        return None

    yaml_buffer = [
        f"# Auto-generated spec suites for module: {mod['module_key']} (Model: {model_alias})",
    ]

    for definition in definitions:
        target_payload = json.dumps(definition, indent=2, ensure_ascii=False)
        try:
            yaml_snippet = call_ollama(
                model_alias,
                skill_prompt,
                target_payload,
                model_map,
            )
            yaml_buffer.append(yaml_snippet)
        except OllamaGenerationError as err:
            print(
                f"   [ERROR] Generation failed for {mod['module_key']}.{definition['name']}: {err}",
            )
            return None  # Signal failure

    return "\n\n".join(yaml_buffer) + "\n"


def _process_model_group(
    model_alias: str,
    mods: list[dict[str, Any]],
    skill_prompt: str,
    model_map: dict[str, str] | None,
) -> None:
    """Processes a group of modules with a specific model.

    Args:
        model_alias: The alias of the model to use for this batch.
        mods: A list of modules to be processed by this model.
        skill_prompt: The main prompt with instructions for the model.
        model_map: An optional dictionary to map model aliases to actual model names.
    """
    print(f"\nProcessing batch with model: {model_alias}")
    for mod in mods:
        if yaml_content := _generate_yaml_for_module(
            mod,
            model_alias,
            skill_prompt,
            model_map,
        ):
            yaml_file = mod["yaml_path"]
            yaml_file.parent.mkdir(parents=True, exist_ok=True)
            with open(yaml_file, "w", encoding="utf-8") as f:
                f.write(yaml_content)
            print(f"   [OK] Suite generated successfully at: {yaml_file}")


def main():
    """Parses command-line arguments and runs the main pipeline."""
    parser = argparse.ArgumentParser(
        description="Automated Test Generation Orchestrator with Ollama",
    )
    parser.add_argument(
        "mode",
        nargs="?",
        default="R",
        choices=["R", "r", "M", "m"],
        help="Generation mode: 'R' (Returns/Skeletons) or 'M' (Mutations/Real Code). Default: R",
    )
    args = parser.parse_args()

    try:
        run_pipeline(mode=args.mode)
    except (FileNotFoundError, ValueError) as e:
        print(f"Configuration Error: {e}", file=sys.stderr)
        sys.exit(1)
    except OllamaGenerationError as e:
        print(f"API Generation Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
